apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-restful-crud.fullname" . }}
  labels:
  {{- include "simple-restful-crud.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "simple-restful-crud.serviceAccountName" . }}

type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
