apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-restful-crud.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "simple-restful-crud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "simple-restful-crud.selectorLabels" . | nindent 4 }}
