{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-restful-crud.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "simple-restful-crud.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
