apiVersion: v2
name: simple-restful-crud
description: A Helm chart for Kubernetes

dependencies:
  - name: postgresql
    version: 10.13.8
    repository: https://charts.bitnami.com/bitnami
  - name: kube-prometheus-stack
    version: 21.0.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: ingress-nginx
    version: 4.0.12
    repository: https://kubernetes.github.io/ingress-nginx
  #- name: metallb
  #  version: 0.11.0
  #  repository: https://metallb.github.io/metallb

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.3"
