# You can use this docker-compose to deploy application in the Docker environment locally with hardcoded accesses
version: "3.7"
services:
  web:
    build: .
    image: redestroyder/simple_restful_crud:0.0.1-ALPHA
    environment:
      - DATASOURCE_POSTGRES_HOST=db
      - DATASOURCE_POSTGRES_PORT=5432
      - DATASOURCE_POSTGRES_DATABASE=arch_homework
      - DATASOURCE_POSTGRES_USERNAME=postgres
      - DATASOURCE_POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      backend: {}

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    networks:
      backend: {}

volumes:
  postgres-data:
      name: otus-min-app-postgres-data

networks:
  backend:
    driver: bridge
    attachable: false
    ipam:
      config:
        - subnet: 100.10.0.0/16
