spring:
  datasource:
    url: jdbc:postgres://${DATASOURCE_POSTGRES_HOST}:${DATASOURCE_POSTGRES_PORT}/${DATASOURCE_POSTGRES_DATABASE}
    username: ${DATASOURCE_POSTGRES_USERNAME}
    password: ${DATASOURCE_POSTGRES_PASSWORD}
