spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/arch_homework
    username: postgres
    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/arch_homework
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    change-log: classpath:/liquibase/changelog-master.yaml
